// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szaepbuuodsulvnjltqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6YWVwYnV1b2RzdWx2bmpsdHFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNjk4MTEsImV4cCI6MjA1NTY0NTgxMX0.rqh8n2sWP3xaKe0ITkVuAidJ5dsAtX1k0xajCCoDXfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);